### PR TITLE
Preprocess all data

### PR DESCRIPTION
**Pull request by codercahol**
branch for odd fixes and running the database generation code on the cluster

### CODE REVIEW

**Comment by murraycutforth** [comment]
@codercahol okay so I'm hesitant to merge this in, because I'm running the database creation code now without all the try/except blocks around the assertions which are on this branch. I think the assertions are basically working correctly so they should be left in to catch errors.

**Comment by codercahol** [comment]
Ok great! There is still the date format commit in there which should still be applicable

**Comment by codercahol** [comment]
But that's like a one liner that I can just extract and add to yours

**Comment by murraycutforth** [comment]
Okay cool. Sorry about the file naming confusion. I do think having this on the cluster is really good, maybe in a week or two we can get together and set up a cron job on the cluster to create the database, and implement some correctness checks, like checking it creates identical results to the version running on my laptop?

**Pull request closed without merging**
